# -*- coding: utf-8 -*-
"""aula4-questao3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v5lqOGHyhU-hqvS4QI8wjo0cMX6dRDGF
"""

horas_trabalhadas = [40, 37, 45, 40, 40, 48]
ganho_por_hora = 20
hora_extra = 25

pagamentos = [
    ganho_por_hora * min(h, 40) + hora_extra * max(0, h - 40)
    for h in horas_trabalhadas
]

print(pagamentos)