# -*- coding: utf-8 -*-
"""aula3_questao2.

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OtvNoPGGD80PudjDWp9Xsti8bBOiiuWo
"""

urls = ["www.google.com", "www.gmail.com", "www.github.com", "www.reddit.com", "www.yahoo.com"]

dominios = [url[4:-4] for url in urls]  # remove os 4 primeiros e 4 últimos caracteres

print("dominios:", dominios)