# -*- coding: utf-8 -*-
"""aula4_questao1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1143nfGRIy0mNyp5FZ4apFIn2iZmRmS4V
"""

# 1. Todos os números pares entre 20 e 50 (inclusive)
pares_20_50 = [x for x in range(20, 51) if x % 2 == 0]

# 2. Os quadrados dos valores da lista [1,2,3,4,5,6,7,8,9]
lista_original = [1,2,3,4,5,6,7,8,9]
quadrados = [x**2 for x in lista_original]

# 3. Todos os números entre 1 e 100 divisíveis por 7
div7 = [x for x in range(1, 101) if x % 7 == 0]

# 4. Para os valores em range(0,30,3), escrever "par" ou "impar"
paridade = ["par" if x % 2 == 0 else "impar" for x in range(0, 30, 3)]

# Mostrar resultados
print("Números pares entre 20 e 50:", pares_20_50)
print("Quadrados de 1 a 9:", quadrados)
print("Números entre 1 e 100 divisíveis por 7:", div7)
print("Paridade dos números em range(0,30,3):", paridade)