# -*- coding: utf-8 -*-
"""aula4_questao4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gh0qxAfX7zN9ATJgim_Km56i57yZkzR5
"""

alunos = ["Maria", "Jose", "Carla", "Sol"]
notas = [35, 50, 20, 80]

aprovados = [alunos[i] for i in range(len(notas)) if notas[i] >= 60]

print(aprovados)