# -*- coding: utf-8 -*-
"""aula4_questao2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Bwhz-OCplu4vGwujROu86P9HJnHLe58s
"""

frase = input("Digite uma frase: ")

vogais = sorted([letra.lower() for letra in frase if letra.lower() in "aeiou"])
consoantes = [letra for letra in frase if letra.isalpha() and letra.lower() not in "aeiou"]

print("Vogais:", vogais)
print("Consoantes:", consoantes)