# -*- coding: utf-8 -*-
"""aula4_questao1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NzmtRj27PUdT3Crrn8aa3_dbOtVs5Eqv
"""

import os

# Solicita uma frase do usuário
frase = input("Digite uma frase: ")

# Define o nome do arquivo
nome_arquivo = "frase.txt"

# Salva a frase no arquivo
with open(nome_arquivo, "w", encoding="utf-8") as f:
    f.write(frase)

# Obtém o caminho absoluto do arquivo
caminho_completo = os.path.abspath(nome_arquivo)

print(f"Frase salva em {caminho_completo}")