# -*- coding: utf-8 -*-
"""aula2_questao1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13cnM5NDsUhBOR5_GJFxPbm3CeWqHqEU0
"""

def data_por_extenso(data):
    meses = ["Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho",
             "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro"]

    dia, mes, ano = data.split('/')
    mes_extenso = meses[int(mes) - 1]

    print(f"Você nasceu em {dia} de {mes_extenso} de {ano}.")