# -*- coding: utf-8 -*-
"""aula4_questao4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NzmtRj27PUdT3Crrn8aa3_dbOtVs5Eqv
"""

import random

# Função para carregar as palavras do arquivo
def carregar_palavras():
    with open("gabarito_forca.txt", "r", encoding="utf-8") as f:
        palavras = [linha.strip().lower() for linha in f if linha.strip()]
    return palavras

# Função para carregar os estágios do enforcado
def carregar_enforcado():
    with open("gabarito_enforcado.txt", "r", encoding="utf-8") as f:
        conteudo = f.read().split("=========")
        estagios = [parte.strip() + "\n=========" for parte in conteudo if parte.strip()]
    return estagios

# Função para imprimir o estágio atual do enforcado
def imprime_enforcado(erros, estagios):
    print(estagios[erros])

# Função principal do jogo
def jogar_forca():
    palavras = carregar_palavras()
    estagios = carregar_enforcado()
    palavra = random.choice(palavras)
    letras_descobertas = ["_" for _ in palavra]
    letras_usadas = []
    erros = 0
    max_erros = 6

    print("\n🎯 Jogo da Forca!")
    print("A palavra tem", len(palavra), "letras.")

    while erros < max_erros and "_" in letras_descobertas:
        print("\nPalavra: ", " ".join(letras_descobertas))
        letra = input("Digite uma letra: ").lower()

        if not letra.isalpha() or len(letra) != 1:
            print("Digite apenas uma letra válida.")
            continue

        if letra in letras_usadas:
            print("Você já tentou essa letra.")
            continue

        letras_usadas.append(letra)

        if letra in palavra:
            for i, l in enumerate(palavra):
                if l == letra:
                    letras_descobertas[i] = letra
            print("✅ Letra correta!")
        else:
            erros += 1
            print("❌ Letra errada.")
            imprime_enforcado(erros, estagios)

    if "_" not in letras_descobertas:
        print("\n🎉 Parabéns! Você acertou a palavra:", palavra)
    else:
        print("\n💀 Você perdeu! A palavra era:", palavra)

# Iniciar o jogo
jogar_forca()