# -*- coding: utf-8 -*-
"""aula1_questao4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13cnM5NDsUhBOR5_GJFxPbm3CeWqHqEU0
"""

numero = input("Digite o número: ")

# Verifica se o número tem apenas 8 dígitos
if len(numero) == 8:
    numero = "9" + numero

# Verifica se agora tem 9 dígitos e se o primeiro é 9 (opcional)
if len(numero) == 9:
    if numero[0] == "9":
        numero_formatado = numero[:5] + "-" + numero[5:]
        print("Número completo:", numero_formatado)
    else:
        print("Número inválido: não começa com 9.")
else:
    print("Número inválido: deve ter 8 ou 9 dígitos.")