# -*- coding: utf-8 -*-
"""aula1_questao7

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13cnM5NDsUhBOR5_GJFxPbm3CeWqHqEU0
"""

def encrypt_fixed(lista_de_nomes, chave=5):
    criptografados = []

    for nome in lista_de_nomes:
        novo_nome = ''
        for c in nome:
            codigo = ord(c)
            if 33 <= codigo <= 126:
                novo_codigo = codigo + chave
                if novo_codigo > 126:
                    novo_codigo = 33 + (novo_codigo - 127)
                novo_nome += chr(novo_codigo)
            else:
                novo_nome += c
        criptografados.append(novo_nome)

    return criptografados, chave

# Lista fornecida
nomes = ["Barabara", "Victoria", "Emanuele", "Carlos", "Maitê", "Ellis"]

# Criptografar com chave 5
criptografados, chave = encrypt_fixed(nomes, chave=5)

# Mostrar resultado
print("Chave:", chave)
print("Nomes criptografados:", criptografados)