# -*- coding: utf-8 -*-
"""aula4_questao3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NzmtRj27PUdT3Crrn8aa3_dbOtVs5Eqv
"""

import re

# Abre o arquivo de roteiro
with open("estomago.txt", "r", encoding="utf-8") as f:
    linhas = f.readlines()

# 1. Imprimir as primeiras 25 linhas
print("Primeiras 25 linhas:\n")
for linha in linhas[:25]:
    print(linha.strip())

# 2. Contar número total de linhas
print(f"\nNúmero total de linhas: {len(linhas)}")

# 3. A linha com mais caracteres
linha_maior = max(linhas, key=lambda l: len(l.strip()))
print(f"\nLinha com mais caracteres ({len(linha_maior.strip())}):")
print(linha_maior.strip())

# 4. Contar menções a Nonato e Íria (sem pegar partes de outras palavras)
texto = " ".join(linhas)
nonato = len(re.findall(r'\bnonato\b', texto, flags=re.IGNORECASE))
iria = len(re.findall(r'\bíria\b', texto, flags=re.IGNORECASE))

print(f"\nNúmero de vezes que 'Nonato' aparece: {nonato}")
print(f"Número de vezes que 'Íria' aparece: {iria}")