# -*- coding: utf-8 -*-
"""aula2_questao2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13cnM5NDsUhBOR5_GJFxPbm3CeWqHqEU0
"""

def substituir_vogais(frase):
    vogais = "aeiouAEIOU"
    modificada = ''.join(['*' if letra in vogais else letra for letra in frase])
    print(f"Frase modificada: {modificada}")

# Exemplo:
frase = input("Digite uma frase: ")
substituir_vogais(frase)