# -*- coding: utf-8 -*-
"""aula2_questao3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13cnM5NDsUhBOR5_GJFxPbm3CeWqHqEU0
"""

import string

def eh_palindromo(frase):
    frase_limpa = ''.join(
        c.lower() for c in frase if c.isalnum()
    )
    return frase_limpa == frase_limpa[::-1]

while True:
    entrada = input('Digite uma frase (digite "fim" para encerrar): ')
    if entrada.lower() == "fim":
        break
    if eh_palindromo(entrada):
        print(f'"{entrada}" é palíndromo\n')
    else:
        print(f'"{entrada}" não é palíndromo\n')