# -*- coding: utf-8 -*-
"""aula1_questao1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EX-mK2ZeRqwtjSOMvNWsS5ijVxax-N25
"""

nome = input("Digite seu nome: ")

for i in range(1, len(nome) + 1):
    print(nome[:i])