# -*- coding: utf-8 -*-
"""aula4_questao5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NzmtRj27PUdT3Crrn8aa3_dbOtVs5Eqv
"""

livros = [
    ("Diário de um Banana: Rodrick é o Cara", "Jeff Kinney", 2007, 224),
    ("Diário de um Banana: A Gota D'Água", "Jeff Kinney", 2007, 217),
    ("Diário de um Banana: A Verdade Nua e Crua", "Jeff Kinney", 2008, 217),
    ("Diário de um Banana: Vai ou Racha", "Jeff Kinney", 2009, 217),
    ("Diário de um Banana: Caindo na Estrada", "Jeff Kinney", 2011, 217),
    ("Diário de um Banana: Um Bromance Muito Louco", "Jeff Kinney", 2011, 224),
    ("Diário de um Banana: Duro de Quebrar", "Jeff Kinney", 2012, 224),
    ("Diário de um Banana: Meltdown", "Jeff Kinney", 2013, 224),
    ("Diário de um Banana: Maré de Azar", "Jeff Kinney", 2014, 224),
    ("Diário de um Banana: Pode Chegar a Tempestade", "Jeff Kinney", 2015, 224),
]

with open("meus_livros.csv", "w", encoding="utf-8") as f:
    f.write("Título,Autor,Ano de publicação,Número de páginas\n")
    for livro in livros:
        linha = f"{livro[0]},{livro[1]},{livro[2]},{livro[3]}\n"
        f.write(linha)

print("Arquivo 'meus_livros.csv' criado com sucesso!")