# -*- coding: utf-8 -*-
"""aula1_questao3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13cnM5NDsUhBOR5_GJFxPbm3CeWqHqEU0
"""

frase = input("Digite a frase: ")

espacos = frase.count(' ')

print(f"Espaços em branco: {espacos}")