# -*- coding: utf-8 -*-
"""aula1_questao5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13cnM5NDsUhBOR5_GJFxPbm3CeWqHqEU0
"""

frase = input("Digite uma frase: ")

vogais = "aeiouAEIOU"
indices_vogais = []

for i, letra in enumerate(frase):
    if letra in vogais:
        indices_vogais.append(i)

print(f"{len(indices_vogais)} vogais")
print(f"Índices {indices_vogais}")