# -*- coding: utf-8 -*-
"""aula2_questao5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13cnM5NDsUhBOR5_GJFxPbm3CeWqHqEU0
"""

import random

def embaralhar_palavras(frase):
    palavras = frase.split()
    resultado = []

    for palavra in palavras:
        if len(palavra) <= 3:
            resultado.append(palavra)
        else:
            miolo = list(palavra[1:-1])
            random.shuffle(miolo)
            nova_palavra = palavra[0] + ''.join(miolo) + palavra[-1]
            resultado.append(nova_palavra)

    return ' '.join(resultado)

# Exemplo de uso:
frase = "Python é uma linguagem de programação"
print(embaralhar_palavras(frase))