# -*- coding: utf-8 -*-
"""aula1_questao2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PdqbBjLbOw1jEPA0k6-PjtTZRhx-j7hN
"""

primeiro_nome = input("Digite seu primeiro nome: ")
sobrenome = input("Digite seu sobrenome: ")

print(f"Bem-vinda, {primeiro_nome} {sobrenome}!")