# -*- coding: utf-8 -*-
"""aula4_questao2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NzmtRj27PUdT3Crrn8aa3_dbOtVs5Eqv
"""

import re

# Lê o conteúdo do arquivo frase.txt
with open("frase.txt", "r", encoding="utf-8") as f:
    frase = f.read()

# Remove tudo que não for letra (mantendo letras acentuadas e espaço)
palavras = re.findall(r'\b[a-zA-ZÀ-ÿ]+\b', frase)

# Escreve as palavras no arquivo palavras.txt, uma por linha
with open("palavras.txt", "w", encoding="utf-8") as f:
    for palavra in palavras:
        f.write(palavra + "\n")

# Mostra o conteúdo do arquivo palavras.txt
with open("palavras.txt", "r", encoding="utf-8") as f:
    print(f.read())