# -*- coding: utf-8 -*-
"""aula1_questao6

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13cnM5NDsUhBOR5_GJFxPbm3CeWqHqEU0
"""

def encontrar_anagramas(frase, objetivo):
    objetivo_ordenado = sorted(objetivo.lower())
    palavras = frase.split()
    anagramas = []

    for palavra in palavras:
        if sorted(palavra.lower()) == objetivo_ordenado:
            anagramas.append(palavra)

    return anagramas

# Entrada do usuário
frase = input("Digite uma frase: ")
objetivo = input("Digite a palavra objetivo: ")

# Resultado
anagramas = encontrar_anagramas(frase, objetivo)
print(f"Anagramas: {anagramas}")