# -*- coding: utf-8 -*-
"""aula2_questao4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13cnM5NDsUhBOR5_GJFxPbm3CeWqHqEU0
"""

import string

def validador_senha(senha):
    if len(senha) < 8:
        return False

    tem_maiuscula = any(c.isupper() for c in senha)
    tem_minuscula = any(c.islower() for c in senha)
    tem_digito = any(c.isdigit() for c in senha)
    tem_especial = any(c in string.punctuation for c in senha)

    return tem_maiuscula and tem_minuscula and tem_digito and tem_especial

# Solicita 4 senhas do usuário
for i in range(1, 5):
    senha = input(f"Digite a {i}ª senha: ")
    if validador_senha(senha):
        print("Senha Válida ✅\n")
    else:
        print("Senha Inválida ❌\n")