# -*- coding: utf-8 -*-
"""aula4_questao6

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NzmtRj27PUdT3Crrn8aa3_dbOtVs5Eqv
"""

import csv

top_musicas_por_ano = []
musicas_ano = {}

with open("spotify-2023.csv", "r", encoding="latin-1") as f:
    leitor = csv.DictReader(f)
    for linha in leitor:
        # Ignorar linhas que tenham aspas dentro dos campos já é tratado pelo csv
        # Só precisa filtrar os anos e converter streams para int, tratando erro
        try:
            released_year = int(linha['released_year'])
            streams = int(linha['streams'])
        except ValueError:
            # Se der erro na conversão, pula a linha
            continue

        if 2012 <= released_year <= 2022:
            if (released_year not in musicas_ano) or (streams > musicas_ano[released_year][3]):
                track_name = linha['track_name']
                artist_name = linha['artist(s)_name']
                musicas_ano[released_year] = [track_name, artist_name, released_year, streams]

for ano in range(2012, 2023):
    if ano in musicas_ano:
        top_musicas_por_ano.append(musicas_ano[ano])

print(top_musicas_por_ano)