input("Digite o nome do produto 1: ")
preco1 = float(input("Digite o preço unitário do produto 1: ").replace(",", "."))
qtd1 = int(input("Digite a quantidade do produto 1: "))
input("Digite o nome do produto 2: ")
preco2 = float(input("Digite o preço unitário do produto 2: ").replace(",", "."))
qtd2 = int(input("Digite a quantidade do produto 2: "))
input("Digite o nome do produto 3: ")
preco3 = float(input("Digite o preço unitário do produto 3: ").replace(",", "."))
qtd3 = int(input("Digite a quantidade do produto 3: "))
total = (preco1 * qtd1) + (preco2 * qtd2) + (preco3 * qtd3)
print(f"Total: R${total:,.2f}".replace(",", "X").replace(".", ",").replace("X", "."))